# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dc6eff5c2a3965030c46c597d57aef2aee796c7fe601ff8b17122d6405252d3673c92ac928e67f6817c3970f7762dead833c79f4a70dfe6ff7b026b6fb52d0e

test:
  secret_key_base: e1d5b48c56e28f34e21c3a721580ebb7e5a2b893dbd3158a582a85c95200bdaf6271f35a0e784cbfe210d15221eb4ae37d944cc6b8349320be87bfd45fa52984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
