Question.create prompt: "Have you ever been pulled over by a cop? Story?", category: "casual"
Question.create prompt: "What is the weirdest prank call you ever made?", category: "casual"
Question.create prompt: "What was your first thought this morning?", category: "Casual"
Question.create prompt: "If you could lock anyone in a room to torment for a day, who would it be? How might you torment them?", category: "casual"
Question.create prompt: "Pick a programing language and write a program that can take any string and make it sound like a pirate said it.", category: "coding"
Question.create prompt: "Explain a SQL inner-join in 30 words or less.", category: "coding"
Question.create prompt: "Pick a programing language. Write a method that takes an unknown number of arguments of strings are returns a single string.", category: "coding"
Question.create prompt: "Explain recursion in 30 words or less.", category: "coding"
Question.create prompt: "Jane Austen or Jane Eyre? Why?", category: "Literature"
Question.create prompt: "The best heroine in YA fiction?", category: "Literature"